# Setup
title:               Competitive Programming
tagline:             'Solutions'
description:         'A static blog for my <a href="https://github.com/dgcnz/competitive-programming" target="_blank">competitive programming solutions</a> repository.'
# url:                 http://lanyon.getpoole.com
url:                 https://dgcnz.github.io
# baseurl:             'https://dgcnz.github.io/competitive-programming/'
baseurl:             /competitive-programming
paginate:            10
permalink:           pretty
exclude:             ['xml/', 'Doxyfile', 'generate_pages.py', 'utils/']

# About/contact
author:
  name:              Diego Canez
  url:               https://github.com/dgcnz
  email:             canezdiego@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
